### ISSUE TITLE
Add additional information fields in submission form

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#10]
The basic information that is needed from the volunteer with each leg of their trip is as follows: 
Dates of Travel 
Where they will be going
Contact information for where they will be going
Hotel/Hostel information
Travel Companions - contact information

![screenshot 2016-01-23 at 9 32 31 am](https://cloud.githubusercontent.com/assets/2973990/12530765/44687c1c-c1b7-11e5-8cf8-0612f1602ba9.png)

As currently implemented, we have Dates of Travel, Country and reason for leave. We need to include fields for all of the information.

**Comment by colinking** [comment]
@SeanBae implemented the new fields in the most recent version of the site on master. Here's a look at it: 

![image](https://cloud.githubusercontent.com/assets/2907397/12773872/c9ad289c-ca0d-11e5-85b5-4c21a7ed3dc9.png)

I'm going to close this issue, but let us know if you want to change anything about these new fields.
