### ISSUE TITLE
Improved Volunteer Assignment on Submission Form

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#113]
- Only allow assignment to the volunteer who submitted the request (not any other volunteer)
- Change wording to "Assign Peace Corps Member"
- When originally submitting the leave request, the volunteer should not be able to assign themselves

**Comment by colinking** [comment]
@choquette33: quick question, should we use the phrasing "Assign a Reviewer" instead of "Assign a Peace Corps Member"? It is more concise and potentially less confusing (as the assigned volunteer is also a Peace Corps member, etc.).

**Comment by choquette33** [comment]
@colinking I like "assign a reviewer"

**Comment by colinking** [comment]
Fixed in #123
