### ISSUE TITLE
Add "site" to return and leave dates in main form

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#119]
Add "to site" to both the date leaving and date returning. 

Should be:
Date leaving site
[input]

Date returning to site
[input]

![screenshot 2016-05-17 at 9 05 45 am](https://cloud.githubusercontent.com/assets/2973990/15323152/99a340de-1c0e-11e6-9acb-1ae51149bd7d.png)

![screenshot 2016-05-17 at 9 00 38 am](https://cloud.githubusercontent.com/assets/2973990/15323033/eef332ca-1c0d-11e6-8864-d5372bd1e55c.png)

This is at the request of the Botswana staff.

**Comment by choquette33** [comment]
@colinking @SeanBae Just wanted to make sure you saw this, super easy one.

**Comment by colinking** [comment]
I've fixed this locally, and will push it with a few other changes today.

**Comment by colinking** [comment]
Fixed in #123
