### ISSUE TITLE
Peace Corps Travel Notices- Examples

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#12]
This is how they are presented on the intranet: 

There is a list of active travel notices for Peace Corps Countries (where we have volunteers)
![screenshot 2016-01-27 at 10 27 14 pm](https://cloud.githubusercontent.com/assets/2973990/12634177/32a87ffe-c545-11e5-8c11-6f81c1ee8e1c.png)

plus there is a list of active travel notices for non-peace corps countries

![screenshot 2016-01-27 at 10 28 36 pm](https://cloud.githubusercontent.com/assets/2973990/12634221/9ac41b34-c545-11e5-862b-8b77c4f73d7f.png)

When you click on the names of the countries it brings you to a document like these: 

![screenshot 2016-01-27 at 10 34 45 pm](https://cloud.githubusercontent.com/assets/2973990/12634303/46b15d1c-c546-11e5-9421-93778745b2d2.png)
![screenshot 2016-01-27 at 10 33 57 pm](https://cloud.githubusercontent.com/assets/2973990/12634304/46b3cfc0-c546-11e5-955b-098dd6544f4e.png)
![screenshot 2016-01-27 at 10 33 32 pm](https://cloud.githubusercontent.com/assets/2973990/12634302/46b084b4-c546-11e5-8581-990e40397200.png)

**Comment by choquette33** [comment]
This one limits just part of the country to travel - Zanzibar
![screenshot 2016-01-27 at 10 37 52 pm](https://cloud.githubusercontent.com/assets/2973990/12634345/b2b68046-c546-11e5-9078-b40ecfc1af3f.png)

**Comment by choquette33** [comment]
This is an example of the non-peace corps country warnings.... They seem to mirror the state dept warnings, but I will confirm. 
![screenshot 2016-01-27 at 10 45 50 pm](https://cloud.githubusercontent.com/assets/2973990/12634481/e11445f8-c547-11e5-8d07-e087adf5d524.png)

**Comment by choquette33** [comment]
This one is a little more complicated.... and seems to be Peace Corps specific. 
![screenshot 2016-01-27 at 10 49 48 pm](https://cloud.githubusercontent.com/assets/2973990/12634542/648a29de-c548-11e5-9cd4-5cd8f9b104d9.png)

**Comment by colinking** [comment]
Closing since #11 is closed
