### ISSUE TITLE
Headers for .csv user uploads?

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#120]
@colinking @SeanBae - What are the required headers for the .csv user upload tool? I am trying to figure out what data I am going to need to prepare and get it into the right format.

**Comment by colinking** [comment]
You don't need any headers right now. The expected format is "Name, Email, Country Code, Access Level". 

The access level is optional, and will default to the volunteer level if not provided for any given row. You can specify "1" for staff and "2" for admin. 

Here's an example:

```
John Smith, john@test.com, US, 1
Jane Doe, jane@test.com, BW
Jack Williams, jack@test.com, US
Colin King, colin@test.com, US, 2
```
