### ISSUE TITLE
Update Leave Request Button not functioning

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#131]
I am on this page: http://peacecorps-bonvoyage.herokuapp.com/requests/573d21e489e582c720edd260/edit

I changed who the request was assigned to and then went to hit the green update leave request button and nothing happens on the click. 

This is the error that I am getting on the click: 
![screenshot 2016-05-19 at 8 02 18 am](https://cloud.githubusercontent.com/assets/2973990/15392900/0ed2e82a-1d98-11e6-8cb3-291a7fdf614f.png)

**Comment by choquette33** [comment]
@colinking @SeanBae I am getting it to work on new requests so it may just be the old requests that aren't working.

**Comment by colinking** [comment]
@choquette33: It looks like the issue stemmed from having an invalid number (it was set to "Test Contact"). I fixed our sample build scripts, and had to reset some of the data. If you already added the test users for today, then you may need to re-add them.

**Comment by colinking** [comment]
@SeanBae: we may need to add validation to the travel contact field so that this crash does not occur in the future.
