### ISSUE TITLE
Approve and Reassign Function

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#140]
Staff need an easier way to approve and reassign to another staff member. 

I propose three action buttons at the bottom of a request. 
1. Approve and Reassign
   -- Clicking on this button adds a log (or comment) of "[User Name] approved and reassigned to [User Name]" and presents the user with a drop down of potential users to reassign to. 
2. Send Final Approval to PCV
   -- Clicking on this button adds a log (or comment) of "[User Name] sent final approval to [User Name] and triggers the currently implemented approve actions. 
3. Send Denial to PCV
   Same as it is now. 

For the initial UI - Lets move the current edit and delete request buttons to small icons (garbage can and pencil) at the top of the request. 

The two approval buttons should be side by side with the Approve and Reassign button on the left. The Approve and Reassign Button should have a check mark icon on the left of the text and be a lighter green than the Send final approval to PCV. 

The Send Final Approval to PCV button should have a paper airplane icon to the left of the text and be a darker green. 

The Send Denial to PCV button can stay as as but include an X icon to the left of the text. 

Hopefully this will help #111

**Comment by colinking** [comment]
From our conversation, we decided to go with a Bootstrap modal that opens upon clicking "approve" or "deny". The modal would have options to re-assign, add an optional comment or notify the PCV, depending on which action was chosen.

**Comment by colinking** [comment]
Here is a slightly modified plan for how to approve a request:

Instead of separate functions to approve or deny a request, I propose we unify them together. After approving or denying a request, you will do basically the same actions (re-assign, optionally comment, etc.). We can replace the approve/deny buttons with a form like this (that can only be accessed by the reviewer):

![img_4105](https://cloud.githubusercontent.com/assets/2907397/15630866/c460525c-2501-11e6-8742-8b7c45d7a6af.jpg)

Then we introduce the concept of a request being "archived". This is equivalent to the "final approval" that we discussed earlier. If there is no assigned reviewer, then the request is considered archived and the UI would reflect that with a notification at the top of the approval page.

Once in the archived state, further edits could be made, but edits cannot be submitted unless the a new reviewer is selected.

**Comment by colinking** [comment]
I built a functional prototype which we can modify with any feedback you may have. It is deployed, so feel free to test it out. 

There is a new approval form similar to the one above:
![image](https://cloud.githubusercontent.com/assets/2907397/15642530/caf9082e-25fc-11e6-9895-f9911960392c.png)

There is also a "archived" filter on the dashboard.

**Comment by choquette33** [comment]
@colinking - this looks great. I'll play with it some more tonight.

**Comment by colinking** [comment]
Hi @choquette33, just wanted to check in. Have you gotten a chance to test out the new approval functionality?

**Comment by choquette33** [comment]
@colinking - Playing with it now. 

We should probably remove the staff part of this since the reviewer might be a volunteer. 
![image](https://cloud.githubusercontent.com/assets/2973990/15760665/2e45f8e6-28e2-11e6-9699-2dff9d51f490.png)

**Comment by choquette33** [comment]
@colinking - We don't have a way to handle this use case right now: I am a staff member I don't want to approve nor deny the request, but I want to submit a comment and assign the volunteer back as the reviewer.

**Comment by choquette33** [comment]
@colinking - This is a bit of a bug, when I reassigned this request to the volunteer, I got a message that only the assigned staff member could approve it. Doesn't make sense in this case because if I wanted to deny the request I would need wait for the volunteer to re-assign it to me. 

![image](https://cloud.githubusercontent.com/assets/2973990/15761227/0353f540-28e5-11e6-966e-9ddfae02e7e9.png)

**Comment by choquette33** [comment]
@colinking - There really isn't a use case for denying someone and then re-assigning a new reviewer. Denial is final. 

So when deny is checked, the assign a reviewer stuff should disappear, leaving only the add an explanation box and the action button. 

![image](https://cloud.githubusercontent.com/assets/2973990/15761594/12a41172-28e7-11e6-8a0d-d6041fc2f1a0.png)

**Comment by choquette33** [comment]
For the action button at the bottom of the form: 

If denied is selected, the button should read: ::paper airplane icon:: Send Denial to PCV 

If approved is selected AND "none" is selected in the assign a reviewer dropdown: then the action button should read: ::paper airplane icon:: Send Final Approval to PCV

If approved is selected AND another person is selected in the assign a reviewer dropdown, then the action button should read: ::two person icon:: Approve and Reassign

![image](https://cloud.githubusercontent.com/assets/2973990/15761849/727058c6-28e8-11e6-938c-45160dca1cd8.png)

**Comment by choquette33** [comment]
For the option of "none" in the dropdown, add the text: 

"None, this is the final approval"

![image](https://cloud.githubusercontent.com/assets/2973990/15761928/e1ff48e6-28e8-11e6-9b89-53063b10c951.png)

**Comment by choquette33** [comment]
Based on the implementation of all of the above changes, we can remove the **Selecting None will archive the request. 

![image](https://cloud.githubusercontent.com/assets/2973990/15762029/831fa126-28e9-11e6-926a-d15085275b5e.png)

**Comment by choquette33** [comment]
Also- for the volunteer role, the approval form should just go completely away. They never will be able to approve or deny, so no need to show that to them. 

![image](https://cloud.githubusercontent.com/assets/2973990/15761227/0353f540-28e5-11e6-966e-9ddfae02e7e9.png)

**Comment by colinking** [comment]
Here are the following changes that to make:
- Add a "Leave Pending" option, which is checked by default
  - If the pending option is checked, then the option to assign "None" will be removed
    - This option will only be available if "Approve" has been selected
- Remove the ability to assign a volunteer as a reviewer
- If "Deny" is checked, then the re-assignment input will be hidden
- The approval form will be hidden from volunteers
- The submit button's text will be updated to remove references to "archiving"
  - The dashboard will also be updated to no longer use the term "archive"

**Comment by colinking** [comment]
The above changes are now in effect @choquette33. Let me know if you have any feedback.

![image](https://cloud.githubusercontent.com/assets/2907397/16032664/316e803c-31bc-11e6-89d3-96e1b267d0ef.png)
