### ISSUE TITLE
Add Floating Action Button to Dashboard

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#145]
For Volunteer User Roles: Add a floating action button in the bottom right. This should lead to the submit page making it easier for the volunteer to get to their main function: submitting a request. 

![image](https://cloud.githubusercontent.com/assets/2973990/15760273/63a64fec-28e0-11e6-9298-ff1cac65fa21.png)

A nice to have would be if the user does not have a pending request, that they go straight to the /submit page

**Comment by colinking** [comment]
![image](https://cloud.githubusercontent.com/assets/2907397/15988473/2fbb080c-3007-11e6-909d-e45d68df8b76.png)
