### ISSUE TITLE
Turn on SMS notifications

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#157]
SMS notifications are currently not functioning as expected: 

I assumed I would get an sms when I (under a staff role) was assigned to review a submission. I didn't receive that sms.

**Comment by choquette33** [comment]
@SeanBae @colinking I was going to get our PCV trial users set up this week. Have you had the chance to look into this?

**Comment by seanbae** [comment]
@choquette33 I will take a look at this over the weekend.

**Comment by choquette33** [comment]
@SeanBae Any luck?

**Comment by seanbae** [comment]
@choquette33 Sent you an email
