### ISSUE TITLE
Denied Requests Remain as "Pending" in dashboard

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#158]
Despite these requests being denied, they are still showing as pending on the dashboard. 

![image](https://cloud.githubusercontent.com/assets/2973990/17936234/1b66fd2e-69ec-11e6-8040-076590be9a60.png)

As you can see Matildah denied the request (didn't choose to re-assign it) but it was reassigned to her.
![image](https://cloud.githubusercontent.com/assets/2973990/17936323/6a79a79a-69ec-11e6-92c0-8cbe7baf35fd.png)

**Comment by colinking** [comment]
It looks like the front-end incorrectly specified a new reviewer (the current user) which caused the back-end to leave the request as pending. This should be fixed now.
