### ISSUE TITLE
Register Mailgun under peacecorps.com

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#22]
Currently, Mailgun sends emails from projectdelta.io, however it would be best that these emails are sent from an email under peacecorps.com.

**Comment by choquette33** [comment]
We may need a new domain since we won't be able to use Peacecorps.gov

**Comment by colinking** [comment]
Based on our call, it sounds like we are going to move this project under it's own domain. I'm closing this issue and opening a new one.
