### ISSUE TITLE
Add a profile page

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#23]
Provide a profile page, accessible by clicking the user's name at the top right-hand corner (or by a supervisor on the users page), where a user's information is displayed and can be edited.

The current list of profile information to be made available on this page is:
- Name
- Email
- Phone Number
- Country
- Time Zone

**Comment by choquette33** [comment]
We do have a unique ID number per volunteer, NOT staff though. Would that be helpful for the system?

**Comment by colinking** [comment]
Sorry, this should have been closed last week (See: a2e8372166a670f770f968de1e51443a2fd1727e).

The profile page (accessible by clicking your name in the top corner, or a user in the users page) allows users to change their registered profile information, including name, country, phone and email. In the future, we may also want to add the ability to toggle email/phone notifications.

![image](https://cloud.githubusercontent.com/assets/2907397/13382366/d0033a6e-de40-11e5-8c52-1b1ea0318d2d.png)
