### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#24]
Currently, there is no support for non-English languages or complete support for time zones outside of EST. We need to explore changes to be made to support both time zones and (possibly?) languages.

**Comment by choquette33** [comment]
Timezones is a must. Language is only a nice to have. All users will speak English.

**Comment by colinking** [comment]
The backend now stores dates without the time component, where appropriate, to prevent issues relating to timezones affecting what date is shown. Timestamps are stored as UTC dates, and will convert to the local time zone when being displayed.

![2016-02-14 at 7 35 30 pm](https://cloud.githubusercontent.com/assets/2907397/13037607/de73597e-d352-11e5-80b5-57883afffd5f.jpg)

![2016-02-14 at 4 37 41 pm](https://cloud.githubusercontent.com/assets/2907397/13037608/e399ba92-d352-11e5-87ff-33c77bb7a14d.jpg)
