### ISSUE TITLE
Limit accessibility to registration page

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#25]
The registration page should only be accessible with a valid invitation link (to verify access to the email), and the sign-in should only work if the email matches the email that was invited.

**Comment by choquette33** [comment]
Yes, agreed.

**Comment by seanbae** [comment]
Registration page is now only functional with a valid invitation link. Sign-in allows a registration of different emails in case the volunteer desires to use a different email address.

Please re-open this issue if this is a problem.
