### ISSUE TITLE
Add country association to users

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#26]
Volunteers and supervisors both need to be associated with a country which they work within. 

The supervisor dashboard then needs to only show requests that belong to volunteers from within the supervisor's country.

**Proposed behavior on invitation**: When a user is invited by a supervisor, the country that the user will belong to will default to that of the supervisor.

_Could a use case arise where another supervisor would invite a volunteer for another country?_

**Comment by choquette33** [comment]
Users will be added centrally by an admin user so I suggest at the time of user creation a country should be designated for a users.

**Comment by colinking** [comment]
Users are now associated with a country, and when supervisors view the dashboard, they will only see the requests from volunteers who are associated with their country. However, the users page has not yet been updated to allow the country to be set when inviting users.

View as an admin (101 requests):
![image](https://cloud.githubusercontent.com/assets/2907397/13093804/2fd80bd8-d4d5-11e5-960a-79429b901760.png)

View as a supervisor (country = US, 70 requests):
![image](https://cloud.githubusercontent.com/assets/2907397/13093834/51fe460a-d4d5-11e5-9dff-d930a6168dec.png)

**Comment by colinking** [comment]
I finished the new "Add Users" page where a supervisor or admin can upload a file with a list of new users to be added to the system. The page currently accepts a .CSV file in the following format:

```
Name, Email, Country Code, Access Level (Integer 0 for Volunteer, 1 for Supervisor, 2 for Admin)
```

For example,

```
John Doe, john@test.com, US, 1
Jane Smith, jane@test.com, US, 0
```

This would add two users, both associated with the United States, but John is a supervisor and Jane is a volunteer. 

The country code and access level are optional. If the country code is not provided, it defaults to the country of the logged in user. If the access level is not provided, it defaults to volunteer level.

_Note_: Supervisors can only add volunteers, so they can just leave off the access level.

When a file is uploaded (the user can drag and drop a file or click to select one manually), the file is parsed and validated. Any issues, along with the validated data, are shown in the table below. 

Here's what the page looks like:

![image](https://cloud.githubusercontent.com/assets/2907397/13413357/ec877862-df17-11e5-981c-16646a6a6396.png)

This now wraps up this issue, so I am going to close it. However, we still need to connect our welcome emails to this page (#43) and allow users to register from the welcome email (#25).
