### ISSUE TITLE
Notify staff in visiting countries of visiting volunteers

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#27]
via email

**Comment by colinking** [comment]
Would this feature be best implemented as a daily overview email of all new requests of volunteers that would be traveling in the supervisor's country?

**Comment by choquette33** [comment]
just a one time email and sms at the time of approval. 

It would go to all supervisor roles in the country of travel and include all information in the request.

**Comment by seanbae** [comment]
The amount of information in the request(s) most likely won't fit into a single SMS (160 characters).
A detailed report will still be sent through email, but SMS message will only contain a concise notification.

**Comment by choquette33** [comment]
@SeanBae That makes sense.
