### ISSUE TITLE
Login Page Color Scheme

### ISSUE THREAD

**Issue by etan12** [peacecorps/BonVoyage#3]
We finished the login page. What is your opinion of the color scheme? Are they OK?

**Comment by choquette33** [comment]
@etan12 I don't know how to open the app locally to see the login page to comment? Can you give me a screenshot?

**Comment by colinking** [comment]
@choquette33 I created a walkthrough on setting up the project locally (see #5). If you need any help with that, then let me know and I can walk you through it. I also attached a photo here of the current login page.

![login_page](https://cloud.githubusercontent.com/assets/2907397/10265266/bc32feba-69f7-11e5-8bde-fb5ae9f465ba.jpg)

**Comment by choquette33** [comment]
Thanks @colinking -- Looks good to me.
