### ISSUE TITLE
Move BonVoyage under new domain

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#30]
Some possible options:

pcbonvoyage.com
pcbonvoyage.org

**Comment by colinking** [comment]
Based on our previous phone calls, we will move this site under an already existing domain as a subdomain. 

@choquette33, what was the exact domain name that your team already works under? I can't recall the abbreviation.

I would recommend that we make the subdomain something clear and concise, such as:
travel.domain.org
requests.domain.org
leave.domain.org
trips.domain.org

**Comment by choquette33** [comment]
Hey @colinking @furuyahir @SeanBae - meet Gabriel @gabrielkrieshok who is the owner of the domain. I'm not sure what needs to happen for game to point the domain to the app, but I thought I could connect you here if that's what we end up doing.

**Comment by gabrielkrieshok** [comment]
Hi @colinking, @SeanBae, and @furuyahir! Just chatted with @choquette33 -- I actually own peacecorps.me as well, that might be the domain that makes the most sense? So we just need to do a CNAME subdomain redirect to your Heroku instance? Lemme know what you prefer as a name (I'm partial to travel.peacecorps.me but it's up to you all) -- and then the URL of the Heroku app. I think that's all I need!

**Comment by seanbae** [comment]
Please create a CNAME record that has value of **peacecorps-bonvoyage.herokuapp.com**

**Comment by colinking** [comment]
@choquette33 We are going to connect our Heroku instance with Github to make it possible to push the master branch straight to Heroku. To do that, we will need to request access to the peacecorps organization. If that is alright with you, we'll request access (it'll email the owners of the peacecorps organization).

**Comment by choquette33** [comment]
@colinking Sure thing.

**Comment by colinking** [comment]
Great, you should receive an email to grant us access to Peace Corps repositories. Let us know when you get the chance to approve it.

**Comment by choquette33** [comment]
@colinking Did the email already go out? @gabrielkrieshok Did you see anything come across to you?

**Comment by colinking** [comment]
It should have gone out about 4 or 5 days ago, but it is possible that it only shows up in your GitHub dashboard. If so, this page would show you what you would do to approve it: https://help.github.com/articles/approving-third-party-applications-for-your-organization/

**Comment by choquette33** [comment]
@colinking Figured it out and granted you permission. Thanks

**Comment by gabrielkrieshok** [comment]
travel.peacecorps.me has begun redirecting. Let me know if there's anything else!
