### ISSUE TITLE
Adjust the default date-picker leaving date to +30 days from current date. 

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#34]
The user will not submit a request to leave the current date and will most likely be planning a month out. 

![image](https://cloud.githubusercontent.com/assets/2973990/13082199/b270aaf6-d49d-11e5-87e6-411b7938e481.png)

**Comment by colinking** [comment]
The date picker now defaults to the current date + 1 month for the leave date and the return date defaults to this date + 4 days.

![image](https://cloud.githubusercontent.com/assets/2907397/13093169/bd06beea-d4d1-11e5-94b3-1ac7b2162e66.png)
