### ISSUE TITLE
Counterpart checkbox

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#53]
This issue is for discussing the implementation of an e-signature from a volunteer's counterpart upon submission of a leave request.

**Comment by choquette33** [comment]
It seems to be a requirement that we include a way for a user without a touch screen device to attain counterpart signature. 

Two options I can think of...
1. Attach a photo option. This way the PCV could attach a photo of anything proving counterpart approval. 
2. A simple checkbox - "I have received approval from my supervisor at site for the attached leave request "

With the check box option, the signature box would be optional. I am leaning towards that implementation

**Comment by colinking** [comment]
I agree that if we have a checkbox, then the signature becomes extraneous. If getting the signature is important enough, we should provide the signature box + photo option as a fallback, otherwise we should simply stick to a checkbox. So would forgoing the signature be okay?

**Comment by choquette33** [comment]
The check box seems to be the most efficient way of getting it done. Let's go with that. 

I like the language that they are using in some government forms that says "I attest that I have received approval from my supervisor at site for...

**Comment by colinking** [comment]
If a staff member is submitting a request for a volunteer, how should we go about getting counterpart approval?

We could either disable the checkbox, and the volunteer would have to be the one to check it off or we let staff members also check off this box, but we emphasize that checking the box is done in the volunteer's name ("I attest that I (VOLUNTEER NAME) have received approval from my supervisor on site for this leave.")

**Comment by choquette33** [comment]
I am for defaulting to letting the user do what they want. So allowing the staff member to check it if submitting on behalf of the volunteer. We can go forward with the volunteer name thing to mitigate.

**Comment by colinking** [comment]
The checkbox, at the bottom of the submission form:
![image](https://cloud.githubusercontent.com/assets/2907397/14155464/cc48c6ac-f68f-11e5-9950-bd0063e6a6ad.png)

**Comment by choquette33** [comment]
Quick correction: should read _at_ site

**Comment by colinking** [comment]
Good catch. Updated in #62: 
![image](https://cloud.githubusercontent.com/assets/2907397/14160428/54118c30-f6aa-11e5-9d27-50e64d8f580e.png)

**Comment by choquette33** [comment]
How does it work with multiple legs? My expectation would be that I only have to check that box once before submitting all legs.

**Comment by colinking** [comment]
Yep, you only check it once. If you add more legs, it only appears once:
![image](https://cloud.githubusercontent.com/assets/2907397/14160653/a8003804-f6ab-11e5-8911-06aa095aa916.png)

**Comment by colinking** [comment]
@choquette33 Should we require that the user check off that they have approval at submission time? Or should we let them submit a request before they have approval, and then allow them to go back and edit it afterwards?

**Comment by choquette33** [comment]
Let's require it.

**Comment by choquette33** [comment]
@colinking - Quick adjustment based on feedback from the Country Director. 

Let's switch the text of the check box to this: 

I attest that I (John Doe) have received approval from my supervisor at site for this leave and understand that post staff may follow up with my supervisor directly to confirm.

**Comment by colinking** [comment]
Changed:

![image](https://cloud.githubusercontent.com/assets/2907397/14478225/a52078de-00e1-11e6-82ce-c99602031f77.png)
