### ISSUE TITLE
Submit Button (Login Page) Not Working

### ISSUE THREAD

**Issue by Zedive** [peacecorps/BonVoyage#6]
We cannot get a successful post request. 
<img width="1233" alt="screen shot 2015-10-16 at 2 44 20 pm" src="https://cloud.githubusercontent.com/assets/8761018/10550359/8880f5dc-7414-11e5-83f9-d15f1a5ffecf.png">
We suspect router.post('/loginsub',function(req, res) (inside index.js) has a bug. But we cannot locate it exactly because the log output gets wiped out.

**Comment by colinking** [comment]
Hey guys! It looks like I made a small mistake in the code that I shared with you last week. You need to define the resp object (`resp = {}`) before you store values in it.
