### ISSUE TITLE
Scrapers run automatically on Heroku

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#66]
We will need to configure Heroku to automatically run both the Peace Corps scraper and the US travel alert scraper. 
- Peace Corps scraper: every 10 minutes
- US travel alert scraper: every hour

**Comment by colinking** [comment]
The end date also appears to not be taken into account.

It may also be useful to add a start date to the spreadsheet.

**Comment by choquette33** [comment]
@colinking I agree. Start and end date makes sense to me

**Comment by colinking** [comment]
There is now a start and end date column in the spreadsheet ([link](https://docs.google.com/spreadsheets/d/1eQgsc94okiGh40EPfH6uwyq4a0aK45OwF5cFYkTlRlA/edit#gid=0)) and both the US Travel Alerts and Peace Corps alerts are set up to scrape every 10 minutes. So if a staff member makes a change to the spreadsheet, it should reflect on the website within 10 minutes.
