### ISSUE TITLE
Assign a Staff Member acts as input instead of dropdown

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#78]
When signed in as a volunteer... 

![screenshot 2016-04-11 at 5 10 56 pm](https://cloud.githubusercontent.com/assets/2973990/14442554/65d7dc78-0008-11e6-8593-1c100a604e30.png)

Closer - Showing the field. It's just an open text box at this point. 

![screenshot 2016-04-11 at 5 12 04 pm](https://cloud.githubusercontent.com/assets/2973990/14442589/96df3410-0008-11e6-8804-87adb87cd0bd.png)

**Comment by colinking** [comment]
It turns out that the endpoint to get data on users was not available to volunteers (thus the empty list). This has been fixed: 
![image](https://cloud.githubusercontent.com/assets/2907397/14481553/24d1f9ca-0102-11e6-9859-2ad4b9de92f5.png)
