### ISSUE TITLE
Add ability for Staff role to choose a user to request on behalf of. 

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#9]
Currently when you are logged in as a Staff member (not a volunteer) there is still the ability to place a request for leave even though staff user an entirely different system. However, there is still a use case for a staff member placing a leave request on behalf of a volunteer user. 

We would like to add the ability for a Staff user to designate a Volunteer user for which they are placing the request on behalf of.

![screenshot 2016-01-23 at 9 32 31 am](https://cloud.githubusercontent.com/assets/2973990/12530680/6cd1f4ba-c1b4-11e5-9583-536a91f7e8f8.png)

**Comment by colinking** [comment]
Support was just added to do this in 0ef4770cdc8d5c3d62841477edd62c539bee8e26. 
![image](https://cloud.githubusercontent.com/assets/2907397/12791367/ddee83a2-ca74-11e5-8eb3-37c3f6948583.png)
