### ISSUE TITLE
Invited users show up in users page

### ISSUE THREAD

**Issue by colinking** [peacecorps/BonVoyage#93]
Currently, there is no visual record of who has been sent a invitation to join BonVoyage. We should add a display to the users page that shows which users are "pending" registration. It would also be nice to be able to revoke an invitation, in case it is sent to the wrong email. 

@SeanBae do you have any input into how this should be done? I know that a new user is not created for invited users, so should we a) create the new user at invitation time, and then update this object when the accept the invitation or b) pull token data when displaying the users page to make it appear like user objects are already created? I imagine b) is the easier option.

**Comment by seanbae** [comment]
I agree with option b). Current information that we store - name, email, country - should be enough to identify unique pending users.

**Comment by colinking** [comment]
@SeanBae: One thing to consider though is that on the users page, staff/admins can click on users to edit their information, but with pending requests, we would have to modify the profile page to detect if the user is a pending user and then update the token data instead of user data, which gets messy. It may just be cleaner to add a "pending" field to the user objects and then stick with option a). Plus, this would allow staff to add a user and then immediately submit leave requests for them, even before they have signed up on BonVoyage.

What do you think?

**Comment by seanbae** [comment]
@colinking: That's a good point on allowing creation of leave requests immediately after the invitation. In fact, if we are already creating user objects, then we may not even need the invitation tokens & registration page at all (one thing we could do is to generate temporary passwords and send those with the invitation email, although there is a slight security risk).

If we do keep the tokens, then their schema should be changed to hold a reference to the user object so that modification of token data will be unnecessary.

**Comment by colinking** [comment]
@SeanBae: If we were to give temporary passwords, then we would want to force users to change the password immediately, which would just be the same flow as with the token. So it is probably best to just stick with the tokens, since it saves the user from having to type in the temporary password. 

We'll also need to make sure that you can't login as a "pending" user until the registration link has been clicked and the password has been changed, since I assume we would initially set the user password to an empty string/undefined/etc, which could be easily guessed.
