### ISSUE TITLE
DNS records are modified to integrate Mailgun service with peacecorps.me domain

### ISSUE THREAD

**Issue by seanbae** [peacecorps/BonVoyage#96]
All of the BonVoyage emails are currently sent under @projectdelta.io.
In order to send emails with @peacecorps.me, DNS records for peacecorps.me domain must be modified to register with Mailgun service.

I have emailed the new DNS records to be added to @choquette33; please forward the information to @gabrielkrieshok so that he can add these information.

**Comment by colinking** [comment]
@gabrielkrieshok, have you gotten a chance to update the DNS records?

**Comment by gabrielkrieshok** [comment]
Hey guys -- this needs to be talked through a little more. For liability, I'm not comfortable having emails associated with my personal id not actually be managed by me. Working on transferring ownership to someone officially at Peace Corps so I'm not on the hook. Will look into it week of May 9. Other option is to move off peacecorps.me -- would be faster cause you don't have me as a bottleneck. : )

**Comment by choquette33** [comment]
@SeanBae @colinking - we made the transfer from @gabrielkrieshok to myself this afternoon. It is currently in limbo as it transfers from one registrar to another.

**Comment by choquette33** [comment]
@SeanBae Is this all set? Are we good to close?

**Comment by seanbae** [comment]
It appears that the login credentials don't work. Could you reset the CloudFlare password and send us the login information via email?

**Comment by choquette33** [comment]
Just emailed it to you Sean 
On Jun 4, 2016 4:23 PM, Sean Bae notifications@github.com wrote:It appears that the login credentials don't work. Could you reset the CloudFlare password and send us the login information via email?
